services:
  db:
    image: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda_quick
    volumes:
      - "./Banco de Dados/ddl do banco.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/agenda_quick
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend/agenda-quick-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
